/*
Copyright 2020 The Kubernetes Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	k8scnicncfiov1 "github.com/s1061123/macvlan-networkpolicy/pkg/apis/k8s.cni.cncf.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMacvlanNetworkPolicies implements MacvlanNetworkPolicyInterface
type FakeMacvlanNetworkPolicies struct {
	Fake *FakeK8sCniCncfIoV1
	ns   string
}

var macvlannetworkpoliciesResource = schema.GroupVersionResource{Group: "k8s.cni.cncf.io", Version: "v1", Resource: "macvlan-networkpolicies"}

var macvlannetworkpoliciesKind = schema.GroupVersionKind{Group: "k8s.cni.cncf.io", Version: "v1", Kind: "MacvlanNetworkPolicy"}

// Get takes name of the macvlanNetworkPolicy, and returns the corresponding macvlanNetworkPolicy object, and an error if there is any.
func (c *FakeMacvlanNetworkPolicies) Get(name string, options v1.GetOptions) (result *k8scnicncfiov1.MacvlanNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(macvlannetworkpoliciesResource, c.ns, name), &k8scnicncfiov1.MacvlanNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8scnicncfiov1.MacvlanNetworkPolicy), err
}

// List takes label and field selectors, and returns the list of MacvlanNetworkPolicies that match those selectors.
func (c *FakeMacvlanNetworkPolicies) List(opts v1.ListOptions) (result *k8scnicncfiov1.MacvlanNetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(macvlannetworkpoliciesResource, macvlannetworkpoliciesKind, c.ns, opts), &k8scnicncfiov1.MacvlanNetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &k8scnicncfiov1.MacvlanNetworkPolicyList{ListMeta: obj.(*k8scnicncfiov1.MacvlanNetworkPolicyList).ListMeta}
	for _, item := range obj.(*k8scnicncfiov1.MacvlanNetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested macvlanNetworkPolicies.
func (c *FakeMacvlanNetworkPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(macvlannetworkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a macvlanNetworkPolicy and creates it.  Returns the server's representation of the macvlanNetworkPolicy, and an error, if there is any.
func (c *FakeMacvlanNetworkPolicies) Create(macvlanNetworkPolicy *k8scnicncfiov1.MacvlanNetworkPolicy) (result *k8scnicncfiov1.MacvlanNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(macvlannetworkpoliciesResource, c.ns, macvlanNetworkPolicy), &k8scnicncfiov1.MacvlanNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8scnicncfiov1.MacvlanNetworkPolicy), err
}

// Update takes the representation of a macvlanNetworkPolicy and updates it. Returns the server's representation of the macvlanNetworkPolicy, and an error, if there is any.
func (c *FakeMacvlanNetworkPolicies) Update(macvlanNetworkPolicy *k8scnicncfiov1.MacvlanNetworkPolicy) (result *k8scnicncfiov1.MacvlanNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(macvlannetworkpoliciesResource, c.ns, macvlanNetworkPolicy), &k8scnicncfiov1.MacvlanNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8scnicncfiov1.MacvlanNetworkPolicy), err
}

// Delete takes name of the macvlanNetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeMacvlanNetworkPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(macvlannetworkpoliciesResource, c.ns, name), &k8scnicncfiov1.MacvlanNetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMacvlanNetworkPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(macvlannetworkpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &k8scnicncfiov1.MacvlanNetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched macvlanNetworkPolicy.
func (c *FakeMacvlanNetworkPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *k8scnicncfiov1.MacvlanNetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(macvlannetworkpoliciesResource, c.ns, name, pt, data, subresources...), &k8scnicncfiov1.MacvlanNetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*k8scnicncfiov1.MacvlanNetworkPolicy), err
}
